---
- name: Setup a new dev machine
  hosts: "{{ target | default('no_host') }}"
  become: yes
  tasks:
    - name: Add PHP repo
      apt_repository:
        repo: ppa:ondrej/php

    - name: Install PHP 8.1
      apt:
        name: php8.1
        state: latest
        update_cache: true

    - name: Install PHP extensions
      apt:
        pkg:
          - php8.1-bcmath
          - php8.1-cli
          - php8.1-common
          - php8.1-curl
          - php8.1-gd
          - php8.1-intl
          - php8.1-mbstring
          - php8.1-mysql
          - php8.1-xml
          - php8.1-zip

    - name: Download Composer
      script: script/composer.sh

    - name: Move Composer globally
      command: mv composer.phar /usr/local/bin/composer

    - name: Set Composer permissions
      file:
        path: /usr/local/bin/composer
        mode: "a+x"
